from typing import List, Literal
from pydantic import BaseModel, Field

# ============================================================================
# FACT CHECKING SCHEMAS
# ============================================================================

class FactCheckIssue(BaseModel):
    """A single issue found during the audit."""
    claim: str = Field(description="The statement in the blog that is problematic")
    issue_type: Literal["citation_missing", "hallucination", "contradiction", "other"] = Field(
        description="Category of the issue"
    )
    severity: Literal["critical", "minor", "suggestion"] = Field(
        default="minor",
        description="critical=must fix, minor=should fix, suggestion=optional"
    )
    recommendation: str = Field(description="How to fix the issue")

class FactCheckReport(BaseModel):
    """The full audit report generated by the Fact Checker Agent."""
    score: int = Field(description="Quality score from 0-10")
    verdict: Literal["READY", "NEEDS_REVISION"] = Field(
        description="Final decision on publication status"
    )
    issues: List[FactCheckIssue] = Field(
        description="List of issues found (empty if clean)", default=[]
    )